version: "3.7"
services:
  redis:
    image: redis
    container_name: redis
    ports:
    - 6379:6379
    volumes:
    - ./redis/redis.conf:/etc/redis/redis.conf
    - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
